config/routes.rb
Rails.application.routes.draw do

  get 'home/about'
  devise_for :users

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>'users#top'

  resources :users,only: [:index,:show,:edit,:update]

  resources :books
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, length: {in:2..20}
  validates :introduction, length: {maximum: 50}

  has_many :books, dependent: :destroy
  # User1に対して複数のbooksインスタンスを持つ
  # dependent: :destroyの意味
  # Userクラスが消えると、Bookモデルのbooksインスタンスも消える
  attachment :profile_image

  def posts
  return Book.where(user_id: self.id)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!,only: [:index,:show,:edit]

  def top
  end

  def index
  	@users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
  	@user = User.find(params[:id])
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if current_user != @user
  	  redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    @book = @user
    if @user.update(user_params)
       redirect_to user_path(@user), notice: 'You have updated book successfully.'
    else
      render :edit
    end
  end



  private
  def user_params
    params.require(:user).permit(:name,:profile_image,:introduction)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_list.html.erb
<h1>User info</h1>
	<%= attachment_image_tag user, :profile_image, size: "100x100", format: 'jpeg',
	 	class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
<table class="table">
	<tbody>
		<tr></tr>
		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>
		<tr>
	 		<td>Introduction</td>
	 		<td><%= user.introduction %></td>
		</tr>
	</tbody>
</table>
	<div class="row">
	  <% if user.id == current_user.id %>
      <%= link_to "", edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user" %>
      <% else %>
      <%= link_to user_path(user.id) %>
      <% end %>
	</div>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <ul>
        <h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<h2>User info</h2>

<%= form_for(@user) do |f| %>


	<div class="field">
        <label for="user_name">Name</label>
        <%= f.text_field :name, class:"name",id:"user_name"%>
    </div>

	<div class="field">
    	<label for="user_image">Image</label>
    	<%= f.attachment_field :profile_image, class: "user-image" %>
	</div>

    <div class="field">
      <label class="introduction",for="user_introduction">Introduction</label>
	    <%= f.text_area :introduction %><br>
    <div class="actions">
	<%= f.submit 'Update User' %>
      <% end %>
    </div>

app/views/users/index.html.erb
<div class="row">
  <div class="col-xs-3">
<!-- 部分テンプレート(User info&New book) -->
<%= render 'users/list',user:@user %>
<%= render 'books/list',book:@book %>
  </div>

  <div class="col-xs-9">
<!-- User一覧 -->
<h1>Users</h1>

<table>
	<thead>
		<tr>
			<th>Image</th>
			<th>name</th>
		</tr>
	</thead>
	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg',class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %></td>
			<td><%= user.name %></td>
			<td><%= link_to "Show",user_path(user.id) %></td>
		</tr>
		<% end %>
	</tbody>
</table>
</div>
</div>

app/views/users/show.html.erb
<!-- Homeボタン -->
<div class="row">
  <div class="col-xs-3">
	<%= render 'users/list',user:@user %>
	<%= render 'books/list',book:@book %>
  </div>

  <div class="col-xs-9">
	<h2>Books</h2>
	<table class="table table-hover table-inverse">
	<thead>
	  <tr>
	  	<th></th>
		<th>Title</th>
		<th>Opinion</th>
		<th colspan="3"></th>
	  </tr>
	</thead>
	  <tbody>
		<% @user.posts.each do |post| %>
		<tr>
		  <td><%= attachment_image_tag @user, :profile_image, size: "40x40", format: 'jpeg',class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %></td>
		  <td><%= link_to post.title,book_path(post) %></td> <!-- booksのshowへ -->
		  <td><%= post.body %></td>
		</tr>
		<% end %>
	  </tbody>
    </table>
  </div>
</div>

app/views/users/top.html.erb
<div class="row">
  <div class="top-message col-md-offset-3 col-md-6">
    <h1>welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong>  !!</span></h1>
          <p>In  <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>, </p>
          <p>you can share and exchange  your opinions , inpressions , and emotions</p>
          <p> about various books!</p>

    <div class="btn-wrapper">
      <div class="row">
         <%= link_to "Log in",new_user_session_path, class:"btn btn-info col-xs-10 col-xs-offset-1 sign_in" %><br>
      </div>
      <div class="row">
        <%= link_to "Sign Up",new_user_registration_path,class:"btn btn-success col-xs-10 col-xs-offset-1 sign_up" %>
      </div>
    </div>
  </div>
</div>