config/routes.rb
Rails.application.routes.draw do

  get 'home/about'
  devise_for :users

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>'users#top'

  resources :users,only: [:index,:show,:edit,:update]

  resources :books
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    <ul>
    	<h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class="nav navbar-nav navbar-left">
      <span>Bookers</span>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
    <li class="">
      <%= link_to " Home",user_path(current_user.id),class:"glyphicon glyphicon-home home" %>
    </li>
    <li class="">
      <%= link_to " Users",users_path,class:"glyphicon glyphicon-user users" %>
    </li>
    <li class="">
      <%= link_to " Books",books_path,class:"glyphicon glyphicon-book books" %>
    </li>
    <li class="">
      <%= link_to " logout",destroy_user_session_path,method: :delete %>
    </li>

    <% else %>
    <li class="">
      <%= link_to " Home",root_path,class:"glyphicon glyphicon-home home" %>
    </li>
    <li class="">
      <%= link_to " about",home_about_path,class:"glyphicon glyphicon-link about" %>
    </li>
    <li class="">
      <%= link_to " sign up",new_user_registration_path,class:"glyphicon glyphicon-edit sign_up" %>
    </li>
    <li class="">
      <%= link_to " login",new_user_session_path,class:"glyphicon glyphicon-log-in sign_in" %>
    </li>
    <% end %>
      </ul>
    </nav>
  </div>
</header>
<div class="body">
  <div class="container">
    <%= notice %>


    <%= yield %>

  </div>
</div>
<footer>
  <div class="container">
    <div class="row">
      <div class="col-xs-3 col-xs-offset-9">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>
  </body>
</html>